### ISSUE TITLE
Master todo-list for integrating NPZ branch into master

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban-toolbox#66]
Here's what needs to be accomplished before the repo is ready for PR

- [x] add contrast adjustment options for multiple channels
- [x] add overlay adjustment options for multiple channels
- [x] refactor t/z stack splitting to work with in memory arrays
- [x] modify array sizes to be consistent across the entire cropping/slicing process
- [x] allow slicing/cropping to be performed in either order
- [x] allow slices to overlap in z dimension
- [x] helper function to find appropriate file extension for save versions
- [x] create single i/o pipeline that generates unified log file for easy reconstruction
- [x] refactor relabeling functions to work with in-memory arrays
- [x] remove old code
